package main
import("debug/macho";"debug/gosym";"debug/dwarf";"encoding/json";"fmt";"os";"reflect";"strings")
func must(e error){if e!=nil{panic(e)}}
func main(){ a,e:=macho.Open(os.Args[1]);must(e);defer a.Close();b,e:=macho.Open(os.Args[2]);must(e);defer b.Close();
 tables:=make([]*gosym.Table,2);for i,f:=range []*macho.File{a,b}{data,e:=f.Section("__gopclntab").Data();must(e);tables[i],e=gosym.NewTable(nil,gosym.NewLineTable(data,f.Section("__text").Addr));must(e)}
 ta,tb:=tables[0],tables[1];if len(ta.Funcs)!=len(tb.Funcs){panic("function count")};changes:=map[string]int{};var checked uint64
 for i,fa:=range ta.Funcs{fb:=tb.Funcs[i];if fa.Name!=fb.Name||fa.Entry!=fb.Entry||fa.End!=fb.End{panic("function layout changed "+fa.Name)}
 for pc:=fa.Entry;pc<fa.End;pc+=4{af,al,_:=ta.PCToLine(pc);bf,bl,_:=tb.PCToLine(pc);checked++;if af!=bf{panic("source file changed")};if al!=bl{if !strings.HasSuffix(af,"/internal/inbox/inbox.go"){panic(fmt.Sprintf("unexpected line change %s:%d ->%d",af,al,bl))};changes[fmt.Sprintf("%d -> %d",al,bl)]++}}
 }
 da,e:=a.DWARF();must(e);db,e:=b.DWARF();must(e);ra,rb:=da.Reader(),db.Reader();cu:="";var cuFiles []*dwarf.LineFile;attrs:=map[string]int{};entries:=0;var inboxScope []bool;inboxEntries:=map[dwarf.Offset]bool{}
 for{ea,e:=ra.Next();must(e);eb,e:=rb.Next();must(e);if ea==nil||eb==nil{if ea!=nil||eb!=nil{panic("entry count")};break};entries++;insideInbox:=false;if len(inboxScope)>0{insideInbox=inboxScope[len(inboxScope)-1]};if ea.Tag==0{if len(inboxScope)>0{inboxScope=inboxScope[:len(inboxScope)-1]}}else{if origin,ok:=ea.Val(dwarf.AttrAbstractOrigin).(dwarf.Offset);ok{insideInbox=insideInbox||inboxEntries[origin]};insideInbox=insideInbox||strings.HasPrefix(fmt.Sprint(ea.Val(dwarf.AttrName)),"github.com/generalbusiness-ai/tailapps/internal/inbox.");inboxEntries[ea.Offset]=insideInbox;if ea.Children{inboxScope=append(inboxScope,insideInbox)}};if ea.Tag==dwarf.TagCompileUnit{cu=fmt.Sprint(ea.Val(dwarf.AttrName));lr,err:=da.LineReader(ea);must(err);if lr!=nil{cuFiles=lr.Files()}};if ea.Offset!=eb.Offset||ea.Tag!=eb.Tag||ea.Children!=eb.Children||len(ea.Field)!=len(eb.Field){panic("DWARF structure")}
 for i,x:=range ea.Field{y:=eb.Field[i];if reflect.DeepEqual(x,y){continue};sourceFile:="";fileAttr:=dwarf.AttrDeclFile;if x.Attr==dwarf.AttrCallLine{fileAttr=dwarf.AttrCallFile};if n,ok:=ea.Val(fileAttr).(int64);ok&&n>=0&&int(n)<len(cuFiles)&&cuFiles[n]!=nil{sourceFile=cuFiles[n].Name};if x.Attr!=y.Attr||x.Class!=y.Class||(x.Attr!=dwarf.AttrDeclLine&&x.Attr!=dwarf.AttrCallLine&&!(x.Attr==dwarf.AttrStmtList&&y.Val.(int64)-x.Val.(int64)==-14)){panic(fmt.Sprintf("unexpected DWARF change CU=%s file=%s name=%v tag=%s %s: %v ->%v",cu,sourceFile,ea.Val(dwarf.AttrName),ea.Tag,x.Attr,x,y))};attrs[fmt.Sprintf("%s: %s %v -> %v",cu,x.Attr,x.Val,y.Val)]++}
 }
 out:=map[string]any{"function_count":len(ta.Funcs),"instruction_addresses_checked":checked,"source_files_and_function_layout_equal":true,"pc_line_changes_confined_to_inbox_go":changes,"dwarf_entries":entries,"dwarf_changes_source_lines_and_14_byte_line_table_offset_shift":attrs};enc:=json.NewEncoder(os.Stdout);enc.SetIndent("","  ");must(enc.Encode(out))}
