package jsonataddl_test

import (
	"encoding/json"
	"flag"
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/generalbusiness-ai/tailapps/jsonataddl"
)

// The conformance corpus at jsonataddl/corpus freezes the current
// JSONata-with-DDL application semantics as executable cases: compile
// outcomes with pinned identity digests and exact diagnostics, and
// evaluation outcomes with golden logical results. Run with -update-corpus
// to regenerate goldens after a deliberate semantic change; the diff is the
// review surface.
var updateCorpus = flag.Bool("update-corpus", false, "rewrite corpus golden files from current behavior")

const (
	corpusRoot           = "corpus/v1"
	corpusRuntimeProfile = "tailapp-otlp-1.8-json-v1-ddl-jsonata-v206-sqlite-3.53.4@5"
)

type corpusManifest struct {
	Interface   string `json:"interface"`
	Dialect     string `json:"dialect"`
	Application string `json:"application"`
	Compile     struct {
		Outcome    string `json:"outcome"`
		Identity   string `json:"identity,omitempty"`
		Diagnostic string `json:"diagnostic,omitempty"`
	} `json:"compile"`
	Evaluations []struct {
		Name    string `json:"name"`
		Program string `json:"program"`
		Input   string `json:"input"`
		Expect  string `json:"expect"`
		Repeat  int    `json:"repeat,omitempty"`
	} `json:"evaluations,omitempty"`
	// Projection cases run only against the extracted core: they exercise
	// the compiled read plan and the default-deny read authorizer over real
	// SQLite state, then apply the validated mutation plan and freeze the
	// final state. See corpus_projection_test.go.
	Projection []corpusProjectionCase `json:"projection,omitempty"`
}

type corpusProjectionCase struct {
	Name    string         `json:"name"`
	Program string         `json:"program"`
	State   string         `json:"state,omitempty"`
	Event   string         `json:"event,omitempty"`
	Meta    map[string]any `json:"meta,omitempty"`
	// SQL, when set, is attempted directly under the program's read
	// authorizer instead of executing the compiled plan; the golden freezes
	// the denial or the returned rows.
	SQL        string `json:"sql,omitempty"`
	Expect     string `json:"expect"`
	FinalState string `json:"final_state,omitempty"`
}

type corpusIdentity struct {
	Revision             string `json:"revision"`
	RuntimeProfile       string `json:"runtime_profile"`
	StorageSchemaDigest  string `json:"storage_schema_digest"`
	ExportContractDigest string `json:"export_contract_digest"`
}

// compileFunc is the seam the stage-4 differential harness ran two
// implementations through. Since stage 6 one implementation remains: the
// goldens these cases pin were generated by the removed legacy
// implementation and proved identical under the core, so this run is the
// standing proof that the extraction preserved the frozen semantics.
type compileFunc func(files fs.FS, root, name string) (*jsonataddl.Application, error)

func TestConformanceCorpus(t *testing.T) {
	runConformanceCorpus(t, func(files fs.FS, root, name string) (*jsonataddl.Application, error) {
		return jsonataddl.LoadApplication(files, root, name, jsonataddl.Tailapp(), corpusRuntimeProfile)
	})
}

func runConformanceCorpus(t *testing.T, compile compileFunc) {
	entries, err := os.ReadDir(corpusRoot)
	if err != nil {
		t.Fatalf("corpus root: %v", err)
	}
	ran := 0
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		ran++
		t.Run(entry.Name(), func(t *testing.T) {
			runCorpusCase(t, compile, filepath.Join(corpusRoot, entry.Name()))
		})
	}
	if ran == 0 {
		t.Fatal("corpus contains no cases")
	}
}

func runCorpusCase(t *testing.T, compile compileFunc, caseDir string) {
	manifest := readManifest(t, caseDir)
	appDir := filepath.Join(caseDir, manifest.Application)
	compiled, err := compile(os.DirFS(appDir), ".", "corpus-app")

	switch manifest.Compile.Outcome {
	case "error":
		if err == nil {
			t.Fatalf("compile succeeded; the corpus expects an error")
		}
		compareGoldenText(t, filepath.Join(caseDir, manifest.Compile.Diagnostic), err.Error())
		return
	case "ok":
		if err != nil {
			t.Fatalf("compile: %v", err)
		}
	default:
		t.Fatalf("manifest compile outcome %q is not ok or error", manifest.Compile.Outcome)
	}

	identity := identityOf(compiled)
	compareGoldenJSON(t, filepath.Join(caseDir, manifest.Compile.Identity), identity)

	recompiled, err := compile(os.DirFS(appDir), ".", "corpus-app")
	if err != nil {
		t.Fatalf("recompile: %v", err)
	}
	if identityOf(recompiled) != identity {
		t.Fatalf("recompilation changed identity: %#v vs %#v", identityOf(recompiled), identity)
	}

	for _, evaluation := range manifest.Evaluations {
		t.Run(evaluation.Name, func(t *testing.T) {
			if evaluation.Expect == "" {
				t.Fatalf("evaluation must declare an expect golden: %#v", evaluation)
			}
			var input jsonataddl.EvaluationInput
			decodeFile(t, filepath.Join(caseDir, evaluation.Input), &input)
			repeats := evaluation.Repeat
			if repeats < 1 {
				repeats = 1
			}
			first := ""
			for attempt := 0; attempt < repeats; attempt++ {
				outcome := renderOutcome(t, compiled, evaluation.Program, input)
				if attempt == 0 {
					first = outcome
				} else if first != outcome {
					t.Fatalf("repeated evaluation diverged:\n%s\nvs\n%s", first, outcome)
				}
			}
			compareGoldenText(t, filepath.Join(caseDir, evaluation.Expect), first)
		})
	}
}

// renderOutcome gives success and failure one golden representation, so
// -update-corpus regenerates both and any divergence — result values or
// exact diagnostic text — fails the freeze.
func renderOutcome(t *testing.T, compiled *jsonataddl.Application, program string, input jsonataddl.EvaluationInput) string {
	t.Helper()
	result, err := compiled.Evaluate(program, input)
	if err != nil {
		return "ERROR: " + err.Error() + "\n"
	}
	encoded, marshalErr := json.MarshalIndent(result, "", " ")
	if marshalErr != nil {
		t.Fatal(marshalErr)
	}
	return string(encoded) + "\n"
}

func identityOf(compiled *jsonataddl.Application) corpusIdentity {
	return corpusIdentity{
		Revision:             compiled.Revision(),
		RuntimeProfile:       compiled.RuntimeProfile(),
		StorageSchemaDigest:  compiled.StorageSchemaDigest(),
		ExportContractDigest: compiled.ExportContractDigest(),
	}
}

func readManifest(t *testing.T, caseDir string) corpusManifest {
	t.Helper()
	var manifest corpusManifest
	decodeFile(t, filepath.Join(caseDir, "manifest.json"), &manifest)
	if manifest.Application == "" || manifest.Interface == "" || manifest.Dialect == "" {
		t.Fatalf("manifest must declare interface, dialect and application: %#v", manifest)
	}
	return manifest
}

func decodeFile(t *testing.T, path string, target any) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(content, target); err != nil {
		t.Fatalf("%s: %v", path, err)
	}
}

func compareGoldenJSON(t *testing.T, path string, value any) {
	t.Helper()
	encoded, err := json.MarshalIndent(value, "", " ")
	if err != nil {
		t.Fatal(err)
	}
	compareGoldenText(t, path, string(encoded)+"\n")
}

func compareGoldenText(t *testing.T, path, actual string) {
	t.Helper()
	if *updateCorpus {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(actual), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	expected, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("golden %s missing (run go test -run TestConformanceCorpus -update-corpus and review the diff): %v", path, err)
	}
	if string(expected) != actual {
		t.Fatalf("golden %s differs from current behavior:\n--- golden ---\n%s\n--- current ---\n%s", path, expected, actual)
	}
}
